<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>FUSE-fx.DynDB-JSONfs</AssemblyName>
    <RootNamespace>System.Data.Fuse</RootNamespace>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  
  <PropertyGroup>
    <PackageId>FUSE-fx.DynDB-JSONfs</PackageId>
    <Description></Description>
    <Product></Product>
    <Company></Company>
    <Copyright>SmartStandards</Copyright>
    <Version>999.0.0</Version>
    <AssemblyVersion>999.0.0.0</AssemblyVersion>
    <Authors>SmartStandards</Authors>
    <FileVersion>999.0.0.0</FileVersion>
    <PackageTags></PackageTags>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>..\..\dist\bin-net10.0\FUSE-fx.DynDB-JSONfs.xml</DocumentationFile>
    <OutputPath>..\..\dist\bin-net10.0\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>1701;1702;1591</NoWarn>
    <DefineConstants>TRACE;DEBUG;NET5</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\dist\bin-net10.0\</OutputPath>
    <DocumentationFile>..\..\dist\bin-net10.0\FUSE-fx.DynDB-JSONfs.xml</DocumentationFile>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>1701;1702;1591</NoWarn>
    <DefineConstants>TRACE;NET5</DefineConstants>
  </PropertyGroup>

  <Import Project="..\FUSE-fx.DynDB-JSONfs\FUSE-fx.DynDB-JSONfs.projitems" Label="Shared" />

  <ItemGroup>
    <PackageReference Include="FUSE-fx.EntityAnnotations" Version="4.3.0" />
    <PackageReference Include="FUSE-fx.ModelDescription" Version="2.1.0" />
    <PackageReference Include="FUSE-fx.ModelReader" Version="0.2.20" />
    <PackageReference Include="FUSE-fx.RepositoryContract" Version="1.1.0" />
    <PackageReference Include="KornSW.AbstractFileSystem.RepositoryContract" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
