<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>System.Data.Fuse</RootNamespace>
    <IsPackable>false</IsPackable>
    <AssemblyVersion>0.0.0.0</AssemblyVersion>
    <Version>0.0.0</Version>
    <AssemblyName>FUSE-fx.DynDB-JSONfs.Tests</AssemblyName>
    <PackageId>Tests</PackageId>
    <Product>Tests</Product>
    <Company />
    <Authors>Tests</Authors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
    <DefineConstants>DEBUG;TRACE;NET5</DefineConstants>
    <OutputPath>bin\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
    <DefineConstants>TRACE;NET5</DefineConstants>
    <OutputPath>bin\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FUSE-fx.EntityAnnotations" Version="4.3.0" />
    <PackageReference Include="FUSE-fx.ModelDescription" Version="2.1.0" />
    <PackageReference Include="FUSE-fx.ModelReader" Version="0.3.0" />
    <PackageReference Include="FUSE-fx.RepositoryContract" Version="1.1.0" />
    <PackageReference Include="KornSW.AbstractFileSystem.Common" Version="2.2.0" />
    <PackageReference Include="KornSW.AbstractFileSystem.RepositoryContract" Version="2.2.0" />
    <PackageReference Include="MSTest" Version="3.3.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.3.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.3.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SmartStandards.Logging" Version="3.4.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FUSE-fx.DynDB-JSONfs.net8.0\FUSE-fx.DynDB-JSONfs.net8.0.csproj" />
  </ItemGroup>

  <Import Project="..\FUSE-fx.DynDB-JSONfs.Tests\FUSE-fx.DynDB-JSONfs.Tests.projitems" Label="Shared" />

</Project>
