<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <BaseOutputPath>..\..\dist\bin-net6.0</BaseOutputPath>
    <AssemblyName>FUSE-DynDBJSONfs-Demo</AssemblyName>
    <Title>FUSE-fx DynDB-JSONfs Demo</Title>
    <ApplicationIcon>appicon.ico</ApplicationIcon>
    <IsPublishable>False</IsPublishable>
    <PackageId>FUSE-fx.DynDB-JSONfs.DemoApp</PackageId>
    <Authors>SmartStandards</Authors>
    <Company>SmartStandards</Company>
    <Product>FUSE-fx</Product>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BrowserForm.cs" />
    <Compile Remove="BrowserForm.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="BrowserForm.resx" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FUSE-fx.EntityAnnotations" Version="4.3.0" />
    <PackageReference Include="FUSE-fx.ModelDescription" Version="2.1.0" />
    <PackageReference Include="FUSE-fx.ModelReader" Version="0.2.20" />
    <PackageReference Include="FUSE-fx.RepositoryContract" Version="1.1.0" />
    <PackageReference Include="FUSE-fx.WinForms" Version="0.2.0" />
    <PackageReference Include="KornSW.AbstractFileSystem.Common" Version="2.2.0" />
    <PackageReference Include="KornSW.AbstractFileSystem.RepositoryContract" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FUSE-fx.DynDB-JSONfs.net10.0\FUSE-fx.DynDB-JSONfs.net10.0.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\dist\bin-net10.0\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>1701;1702;1591</NoWarn>
    <DefineConstants>TRACE;DEBUG;NET5</DefineConstants>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\dist\bin-net10.0\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>1701;1702;1591</NoWarn>
    <DefineConstants>TRACE;NET5</DefineConstants>
    <Optimize>True</Optimize>
  </PropertyGroup>
  
</Project>